# docker-compose.prod.yml (archivo adicional para producción)
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: proyecto_ati_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password123}@db:5432/proyecto_ati_db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: