version: '3.8'

services:
  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: proyecto_ati_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  # Servicio de aplicación web Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:password123@db:5432/proyecto_ati_db
    depends_on:
      - db
    restart: unless-stopped

# Volumen para persistir datos de PostgreSQL
volumes:
  postgres_data: