# Generated by Django 5.2.3 on 2025-07-10 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LenguajeProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('foto', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('color_favorito', models.CharField(blank=True, max_length=20)),
                ('libro_favorito', models.CharField(blank=True, max_length=100)),
                ('musica_favorita', models.TextField(blank=True)),
                ('videojuegos_favoritos', models.TextField(blank=True)),
                ('password_hash', models.TextField()),
                ('configuracion', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas', to='main_app.usuario')),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibidas', to='main_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('multimedia', models.TextField(blank=True)),
                ('privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enviada_por_correo', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chat')),
                ('de_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='main_app.comentario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_usuario1', to='main_app.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_usuario2', to='main_app.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('usuario1', 'usuario2')},
        ),
        migrations.CreateModel(
            name='UsuarioLenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lenguajeprogramacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'lenguaje')},
            },
        ),
    ]
