# Generated by Django 5.2.3 on 2025-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_usuario_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lenguajes',
            field=models.ManyToManyField(blank=True, through='main_app.UsuarioLenguaje', to='main_app.lenguajeprogramacion'),
        ),
    ]
