# Generated by Django 5.2.3 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_usuario_lenguajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
