# Generated by Django 5.2.3 on 2025-07-24 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_usuario_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_usuario2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudamistad',
            name='de_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudamistad',
            name='para_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
