# Generated by Django 5.2.3 on 2025-07-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_chat_usuario1_alter_chat_usuario2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='lenguajes',
        ),
        migrations.AlterField(
            model_name='chat',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_usuario2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudamistad',
            name='de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudamistad',
            name='para_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='img/default_profile.png', null=True, upload_to='img/'),
        ),
    ]
