# Generated by Django 5.2.3 on 2025-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_usuario_lenguajes_alter_chat_usuario1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='img/default_profile.png', upload_to='img/'),
        ),
    ]
