# Generated by Django 5.2.4 on 2025-08-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_notificacion_actor_alter_notificacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
    ]
